"""fields about_me and last_seen added to User

Revision ID: 56149e2f755f
Revises: d57f94391b81
Create Date: 2022-01-21 08:40:59.421373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56149e2f755f'
down_revision = 'd57f94391b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
